<?php
header("Cache-Control: no cache");
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class="container mt-5 text-light" style="background-color:#000000">

    <div class="row">
        <div class="col-12">
            <div class="row h3">My Playlist</div>
            <div class="row border rounded p-2 mt-4">
                <div class="col-12 p-4">
                    
                    <!-- -------------------------------------------loop starts--------------------------------------->
                    <?php foreach ($myPlaylists->items as $playlist) { ?>

                        <div class="row mt-3">
                            <div class="col-2 h3 m-auto"><?php echo $playlist['name'] ?></div>
                            <div class="col-4 m-auto"></div>
                            <div class="col-3 m-auto"></div>
                            <div class="col-1 mt-3">
                                <!-- -------------------------------------------Form starts--------------------------------------->
                                <?php echo $this->tag->form(['']); ?>
                                <?php echo $this->tag->hiddenField([$playlist['name'], 'name' => 'myPlaylist', 'value' => $playlist['id']]); ?>
                                <?php echo $this->tag->hiddenField([$this->request->get('song'), 'name' => 'song', 'value' => $this->request->get('song')]); ?>
                                <?php echo $this->tag->submitButton(['ADD', 'class' => 'nav nav-link text-white border-0', 'style' => 'background-color:#121212']); ?>
                                <?php echo $this->tag->endForm(); ?>
                                <!-- -------------------------------------------Form ends--------------------------------------->

                            </div>
                        </div>
                    <?php } ?>
                    <!-- -------------------------------------------loop ends--------------------------------------->

                </div>
            </div>

        </div>

    </div>
</body>

</html>