<?php
header("Cache-Control: no cache");
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class="container mt-5 text-light" style="background-color:#000000">

    <div class="h3 my-3"><?php echo $myPlaylist->name; ?></div>

    <!-- -------------------------------------------table starts --------------------------------------->

    <table class="table" style="width:100%;color:white;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Album</th>
                <th scope="col"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                        <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                    </svg>
                </th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <!-- -------------------------------------------loop starts --------------------------------------->
            <?php
            $count = 1;
            foreach ($myPlaylist->tracks['items'] as $track) { ?>
                <tr>
                    <th scope="row"><?php echo $count++; ?></th>
                    <td><img src="<?php echo $track['track']['album']['images'][2]['url'] ?>">&nbsp;&nbsp;<?php echo $track['track']['name'] ?></td>
                    <td><?php echo $track['track']['album']['name'] ?></td>
                    <td><?php
                        //converting duration into minutes
                        $input = $track['track']['duration_ms'];

                        $uSec = $input % 1000;
                        $input = floor($input / 1000);

                        $seconds = $input % 60;
                        $input = floor($input / 60);

                        $minutes = $input % 60;
                        $input = floor($input / 60);

                        $hour = $input;

                        echo sprintf('%2d:%02d',  $minutes, $seconds);

                        ?></td>
                    <td>
                        <!-- -------------------------------------------form starts --------------------------------------->
                        <?php echo $this->tag->form(['playlist/deleteFromPlaylist']); ?>
                        <?php echo $this->tag->hiddenField([$myPlaylist->name, 'name' => 'myPlaylist', 'value' => $myPlaylist->id]); ?>
                        <?php echo $this->tag->hiddenField([$this->request->get('song'), 'name' => 'song', 'value' => $track['track']['uri']]); ?>
                        <?php echo $this->tag->submitButton(['Delete', 'class' => 'nav nav-link text-white border-0', 'style' => 'background-color:#121212']); ?>
                        <?php echo $this->tag->endForm(); ?>
                        <!-- -------------------------------------------form ends --------------------------------------->


                    </td>
                </tr>

            <?php } ?>
            <!-- -------------------------------------------loop ends --------------------------------------->

        </tbody>
    </table>
    <!-- -------------------------------------------table ends --------------------------------------->

</body>

</html>