<?php
header("Cache-Control: no cache");
phpinfo();
die();

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body class="container mt-5 text-light" style="background-color:#000000">


    <?php

    if ($this->session->has('user_id')) {

        echo $this->tag->linkTo(['user/dashboard', 'Dashboard', 'class' => 'btn btn-info mt-2']);
        echo $this->tag->linkTo(['user/logout', 'logout', 'class' => 'btn btn-danger mt-2 mx-5']);
    } else {
        echo $this->tag->linkTo(['user/login', 'Login', 'class' => 'btn btn-info mt-2 ']);
    }


    ?>
    <!-- -------------------------------------------Form starts--------------------------------------->

    <?php echo $this->tag->form(['index/search', 'class' => 'my-4 container text-center  p-4 border', 'method' => 'get']); ?>
    <p class="row">
        <label for="email" class='label col-1 mx-5 h4 text-bold text-light'></label>
        <?php echo $this->tag->textField(['query', 'class' => 'form-control col-6']) ?>
        <?php echo $this->tag->submitButton(['Search', 'class' => 'btn  btn-primary mx-5']); ?>
    </p>
    <!---------------------------checkboxes start -------------------------------->
    <p class='row '>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="track" id="track" name="track" checked>
        <label class="form-check-label" for="Album">
            Track
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="album" id="album" name="album">
        <label class="form-check-label" for="Album">
            Album
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="artist" id="artist" name="artist">
        <label class="form-check-label" for="artist">
            Artist
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="playlist" id="playlist" name="playlist">
        <label class="form-check-label" for="playlist">
            Playlist
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="show" id="show" name="show">
        <label class="form-check-label" for="show">
            Show
        </label>
    </div>
    <div class="form-check text-light">
        <input class="form-check-input" type="checkbox" value="episode" id="episode" name="episode">
        <label class="form-check-label" for="episode">
            Episode
        </label>
    </div>
    </p>
    <!---------------------------checkboxes ends -------------------------------->

    <?php echo $this->tag->endForm(); ?>
    <!-- -------------------------------------------Form ends --------------------------------------->


</body>

</html>