<?php
header("Cache-Control: no cache");
?>

<body class="container mt-5 text-light" style="background-color:#000000">

    <h2 class='row mb-5'>Sign up</h2>
    <!-- checking errors -->
    <?php if (isset($message)) { ?>
        <div class="alert alert-danger">
            <?php echo $message; ?>
        </div>
    <?php } ?>
    <!-- -------------------------------------------form starts --------------------------------------->

    <?php echo $this->tag->form(["", 'class' => 'form justify-content border p-5 ']); ?>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <p>
                <label for="username">Username</label>
                <?php echo $this->tag->textField(["username", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="email">E-Mail</label>
                <?php echo $this->tag->textField(["email", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="email">Password</label>
                <?php echo $this->tag->textField(["password", 'class' => 'form-control']); ?>
            </p>

            <p>
                <label for="email">Alredy User ?</label>
                <?php echo $this->tag->linkTo("login/", "Login"); ?>
            </p>

            <p>
                <?php echo $this->tag->submitButton(["Register", 'class' => 'btn btn-primary']); ?>
            </p>

        </div>
        <div class="col-3"></div>
    </div>
    </form>
    <!-- -------------------------------------------form ends --------------------------------------->

</body>